Include term.h for tigetstr except for slang build.
Fixes
curs_main.c:529:11: warning: implicit declaration of function ‘tigetstr’ [-Wimplicit-function-declaration]

Including it before header.h causes compilation errors because
of "int lines;" in header.h and
in term.h.